package com.ngsb.controller;

import java.security.Principal;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.ngsb.dto.AppUserDto;
import com.ngsb.dto.Message;
import com.ngsb.entity.AppUser;
import com.ngsb.payload.UserRequest;
import com.ngsb.payload.UserResponse;
import com.ngsb.service.IAppUserService;
import com.ngsb.utility.JwtUtil;

@RestController
@RequestMapping("/api/v1/user")
@CrossOrigin
public class AppUserController {

	@Autowired
	private IAppUserService userService;
	
	@Autowired
	private AuthenticationManager authenticationManager;
	
	@Autowired
	private JwtUtil jwtUtil;

	@PostMapping("/save")
	public ResponseEntity<Message> createUser(@RequestBody AppUserDto appUserDto) {
		String resp = userService.createUser(appUserDto);
		return ResponseEntity.ok(new Message("Success", resp));
	}
	
	@GetMapping("/one/{username}")
	public ResponseEntity<AppUser> findUserByUsername(@PathVariable(name = "username") String username){
		 AppUser user = userService.findByUsername(username);
		 return ResponseEntity.ok(user);
	}
	
	@PostMapping("/login")
	public ResponseEntity<UserResponse> loginUser(@RequestBody UserRequest request){
		authenticationManager.authenticate(new UsernamePasswordAuthenticationToken(request.getUsername(), request.getPassword()));
		String token = jwtUtil.generateToken(request.getUsername());
		return ResponseEntity.ok(new UserResponse(token,"GENERATED BY MR. AKASHAHRUKH"));
	}
	
	@PostMapping("/welcome")
	public ResponseEntity<String> readPrincipal(Principal p){
		return ResponseEntity.ok("Hello : "+p.getName());
	}

}
